### ISSUE TITLE
RuntimeError: cuda runtime error (801)

### ISSUE THREAD

**Issue by arkseal** [vietnguyen91/Super-mario-bros-A3C-pytorch#18]
Hi, when I try to run this code using CUDA I always am getting this error. It works fine on CPU and other programs work fine using CUDA. I tried to search online but I didn't find anything of use.
Here's the entire Traceback:
THCudaCheck FAIL file=..\torch/csrc/generic/StorageSharing.cpp line=253 error=801 : operation not supported
Traceback (most recent call last):
  File ".\train.py", line 84, in <module>
    train(opt)
  File ".\train.py", line 73, in train
    process.start()
  File "C:\Users\Aarush\AppData\Local\Programs\Python\Python38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Aarush\AppData\Local\Programs\Python\Python38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Aarush\AppData\Local\Programs\Python\Python38\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Aarush\AppData\Local\Programs\Python\Python38\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\Aarush\Documents\Visual Studio Code\Maching_Learning\machine-learning-env38\lib\site-packages\torch\multiprocessing\reductions.py", line 240, in reduce_tensor 
    event_sync_required) = storage._share_cuda_()
RuntimeError: cuda runtime error (801) : operation not supported at ..\torch/csrc/generic/StorageSharing.cpp:253
(machine-learning-env38) PS C:\Users\Aarush\Documents\Visual Studio Code\Maching_Learning\Super-mario-bros-A3C-pytorch> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Aarush\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Aarush\AppData\Local\Programs\Python\Python38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by qf-123** [comment]
the same problem😟

**Comment by arkseal** [comment]
I think it worked when I used Linux, try using wsl if you want to stay on Windows
